{% set version = "2.0.0" %}

package:
  name: azure-nspkg
  version: {{ version }}

source:
  fn: azure-nspkg-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-nspkg/azure-nspkg-{{ version }}.zip
  md5: fe19ee5d8c66ee8ef62557fc7310f59cffb7230f0a94701eef79f6e3191fdc7b
  
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
  
  run:
    - python
    - setuptools

test:
  imports:
    - azure

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Namespace Package [Internal]'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
