travis:
  secure:
    BINSTAR_TOKEN: ahWQfSrArFmQOyTRrxymKw9O9JOjV5BhGZvuKs5x7wjWNnqn0Jol1QZhUAfi6JWmEzpV8vIXU4WW/ZlohHiKB/Vr7YHoie2gt8eBwMcyhbq41+tyu/M1AxJuXudsMo7nuFPZY0MbQWkDvrkw35MYoKT20DHfzozI46rwYmwmEht+0eizKXokV4SS5cvwfTJFSV9Nk74PSbmshnjkxnlkTPns6sK0BfRdxFfc9lY6s+8vDW/bS5u7PXEY922UN88jy2ASMcGMs5IH4UENm9BeDPATi00IGoHJTazzM1lb6yMwtTyBZKSzePH4FGqyjEFwkFws6waBXkIffaS7Y10HITRJdumDi4QLaXfI2ICnUBdvlhpeCI260gEKHxkmtCco7IUKXUtfH0hgCot0RU8myz4uiVgeNwm+cHTAWS/OdNl8P3NaRtf3T2KOJmKb9XAKjtCjXRXcHHFwZ7VO9rmsIDKUCK66hcKjMyHpWd4sdY6nusSxFiQLlxUXiWeDzs116w5kOlQ6PmeQb/1zGnvKrEe8fXOWIVoS33O7yPad2vezuLZp59jKG1MBg01Vd6Twp8MUTbuIefViRUfO/v0xF1XhmhdSTNin8u7YP+Yz9lJzEeIxkhDhC88+7xLAeQEjBVl0y7qhDUXK0721D2Zhewp83FEi2zF1Qm723d7GrRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
