travis:
  secure:
    BINSTAR_TOKEN: QxvHGXfa+1loTYxBe7fX4yq6RiqQClpPPyTJWQOB7JIMMsPzmhsjCyCjB2El4EJOHFsvvcI6Vz9cx/PA8ebjtL9rO9Px7xRDJceHx2uaVBnWxmK2g9loXgpgh/nHV8Qzzqi9dhNm7QST27AQe9eS/ZQaTw1EESESwJ1zwGoMcQqeLw1370PZp/wealKcczSCZUWmv083sIH5PXAyX0QN0tiy2ICUpX8bAyjcr4acpqS6zCk7lcbssbnmMbfriP2JXxAZQ1WlX8GQtcNt8HEhqjLp+820IH9HSBqelp7mVqU0jtLAIvzVEmyIyESmsWKi4cMf+c/Rd++Ado42p9ZpqgvQMlwB0HfLe4+5IxSn3XBWBSBfkaMWGq5+WzB6IkSNAgNot93GXJ7MyxoBHnJIquXUKVA+OhomRTxA+DfCPMVLXMD8ax4s4LTxx4+JeUuI3Fqpl7FLfQpTXyRLXRn9PHIvx0T3FSejasdlpQnFwKIX/Sn2H40zpTq9hwM94iF+Z9vVtF0yiEKLuj303ixM8g3Z2CUp1i6+9jYhjSM2IYWJknN3kxQd9TJx66tJqVMmReJwKlUxAd+AWxWVR/AunVNJPm+KKQ334KWNgtK3jnBmAQLc3X+q8dtTv2LqMBjdUo6VykEzz5VzFg/GI2xhyKHtKFdHUDqnXlKRKx2n5wk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
