travis:
  secure:
    BINSTAR_TOKEN: aAxYrGtnF2hCiC1iydWrTA+0jcGNSUuS9mxl9XUYCMEXZnB122TTqzmCP5XeBzUPttD0GlNPc7AmuMgNhqHz79cG0udVwFOxXY556E+gZqhHVUfpVnvCPubWLwnWdDp5iTV2RXnQ/Je9RSSkK/FNI7w50pLyQ+Pi6NbgZesBHLETwhI+Ip3MitGaZ7orw7OG7oH+M/nG9Hah7LbIeqiLyMnAIK6qBmP01ZczTUoz5vzRFmk/E935vGdfct/PlHOJ8upocvcHJb7NbzdAE816xl4jtfro/lf3GKsnt8U7QPDgMPhVJHRvx4XQz7AixLTWrrXhm0ntUv9Dy4YuRf741JCtVLpjks/YlEj2r+sYTye8JBJQkzfcmkZl0uE1pFBSQY490+djvUALnVglLxNk40rjvaDZqcX+swmMiqN1UUuItWLfe4DcPGTEl811uBH6NgYnjE6AfLTzJEGog8KfmZa7dI4UaHp8JW31T7YXo03Jb8MCrfhPF0btxIntoQ7nZ7CNNPtar1lq5RLdFQjXo13sR5zYxacLjhLAoycPmGoPrNfXFXHXO0UPKnJbFlfOESzSKKzCTF3e0WF4XmVgAEhu2a62FVHPxwrHgizUI5kn56GYKUosu0FfD/KpE9jAz4XuajnjOt/fVQYWy+1ka/v6RY1IrqIddfFemTdmj8w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
