travis:
  secure:
    BINSTAR_TOKEN: Uqo9VKDHMSP8ObNPnb7BniW6+VxuZZ+YjFglAgQqNXOioSDacAB0j0AoPLE5aqw8JTOl3wbud8s7Bg/aRH8pOf+SrNgIQt93f1lv5HRoV/IqEZcqCC9HIyVSaowLFJtzbNBmM+hydRXLrK3cOLBJkcX6uuKyLW/OLZIyebndauqiTgNBslb+1wiFDFz2ik/ONP04pzB42P6SiIRuq7+hE85f/pomW51kMNbn4wwSQfMPvkIV3mtWe8ZTwK160apTu0W8L2ZIzACt90BGjEMp/FiDb3OZGK5LIqGuFEwRLUgjwht8mbFgkyq+kfegsnDx9X05mKMkIonrl/1jjR81ssU5+xVTSd0VjoG9+QcrzkaiOv0S29XBZkvuY9hu/kKsKPS+0jOSzeQj2aXDTCH+yl3NuDcBx3Pd3qo4IQDp3Urfhn8dLBAtYMb8ZrtPu3/MtgAApeB0e+UMoSOGEm0POe1ttQlfn7BbAlOL6I2iuqlWmVer5sY70iETU4uVS+KUxcj2PQbtf/3316S+xY+3HwHhezaAvRee/+vRwa12o2qxYr6bNRrx3ECJIRC+SR9rj7Lzz1UMk+ch4+Fzr4BDNRuLbHbP+oZEIbYoD2SZIevzR3AN+4zU0xxW3E/ayWxDTb1UuVYjQYKCDx1X+JWj2/87iqvAoYLKeR81lrAm/FE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
